version: '2'

services:

  work-station:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:3000'

#  front:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '9000:3000'
#    environment:
#      - NODE_ENV=development