---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workstationmoh-pvc
  labels:
    app: workstationmoh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi